### ISSUE TITLE
FSharp templates not in Command Palette

### ISSUE THREAD

**Issue by GerjanOnline** [ionide/ionide-yeoman#2]
I have installed the fsharp yeoman generator (https://github.com/fsprojects/generator-fsharp) by doing `npm install -g generator-fsharp` and this was succesful. See:

![image](https://cloud.githubusercontent.com/assets/1153419/10246775/6d381d60-6914-11e5-99f1-9124bcd73d57.png)

But when I try to do this with Ionide by doing:
`ctrl + shift + p > F#: New project > popup`

![image](https://cloud.githubusercontent.com/assets/1153419/10246821/c9eb5f40-6914-11e5-9426-9bfa2dbae926.png)

I do not see fsharp templates here.

Am i missing something?

**Comment by Krzysztof-Cieslak** [comment]
Let's close this one and discuss it in #3 as it is probably same issue.
