### ISSUE TITLE
After clicking on F#: New Project > Select Dir in Command Palette it doesn't continue

### ISSUE THREAD

**Issue by GerjanOnline** [ionide/ionide-yeoman#3]
Possibly related to https://github.com/ionide/ionide-yeoman/issues/2 

Please see:

![fsharp](https://cloud.githubusercontent.com/assets/1153419/10246998/09a81460-6916-11e5-9733-271f5a487127.gif)

What I do:
`ctrl + shift + p > F#: New Project > Select directory > [nothing happens]`

When I go to `packages > atom-yeoman > Toggle`

I will get the Select Directory option again

![fsharp2](https://cloud.githubusercontent.com/assets/1153419/10247077/9f7df46e-6916-11e5-81d0-9471147e5ee5.gif)

But now I do not have fsharp templates (see https://github.com/ionide/ionide-yeoman/issues/2)

I am using Windows 7 btw

@david-driscoll @Krzysztof-Cieslak @cloudRoutine

**Comment by Krzysztof-Cieslak** [comment]
Can You check out newest atom-yeoman update?

**Comment by GerjanOnline** [comment]
Just checked  atom-yeoman 0.3.15

Still the same issue, it does not continue and it does not show F# templates

**Comment by Krzysztof-Cieslak** [comment]
Can You try using this repo - https://github.com/Krzysztof-Cieslak/yeoman-fsharp-cache -  to restore cache of generator .

**Comment by GerjanOnline** [comment]
I tried. Replaced C:\Users\[user]\.cache\yeoman with your repo

Doesn't fix it. Same behaviour

**Comment by koenmetsu** [comment]
Having the same behavior on my Win7 machine. 

Btw `C:\Users\[user]\.cache\yeoman` does not exist after `npm install -g yeoman` and `npm install -g generator-fsharp`.

Created the folder manually then, but same result.

**Comment by koenmetsu** [comment]
Problem also occurs just using `yo fsharp`. This does not do anything. I have a strong suspicion this is due to generator-fsharp not using the npm proxy.

**Comment by jamesjrg** [comment]
I have the same problem on Windows 10, atom-yeoman 0.3.15, ionide-yeoman 1.0.2. It worked when I first installed ionide a couple of weeks ago, but doesn't any longer.

**Comment by mclang** [comment]
Is there any progress with this?
I'm using Windows 10, atom-yeoman 0.3.15, ionide-yeoman 1.0.2 as well.
Do I need to install yeoman and generator-fsharp separately outside Atom Editor, or are both installed as dependency of atom-yeoman and ionide as I think they are?

**Comment by byteit101** [comment]
I have the same issue on a completely fresh atom install on Debian Jessie

**Comment by Krzysztof-Cieslak** [comment]
Sorry about lack of progress with this issue. We are planning to deprecate yeoman support, and move to [Forge](https://github.com/fsprojects/Forge) instead.

**Comment by julien-leclercq** [comment]
Same problem here on ubuntu 14.04 still no news ?

**Comment by adamkes** [comment]
I`m having the same issue. I`m new to F#, Atom and Ionide and I have tried to follow introduction on http://ionide.io/ but once typed F# in Command Palette nothing is happening.  Is yeoman deprecated? If so can you please update http://ionide.io/

**Comment by Tochemey** [comment]
I have the same issue and it seems there is no concern. I am new to F# and already to get a good IDE to work with is an issue.
